### ISSUE TITLE
Docker compose is not working

### ISSUE THREAD

**Issue by kush99993s** [AndreWohnsland/streamlit-page#1]
I ran the following code :

`sudo docker-compose up`

It gives me following error 
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services: 'streamlit'
Unsupported config option for networks: 'traefik-public'

**Comment by AndreWohnsland** [comment]
Sorry the late reply, this project is more a template than a real one for me, so notifications were off. 
If this is still relevant, let me know, otherwise feel free to close this issue.
My guess is that your docker version is too old to support the config. This project was using compose v2.x.x, you can check with `docker-compose --version` which version you are running. I also added the version tag to the files, to further minimize the errors. Using the latest docker / docker-compose version as well as the latest commit should work now.
